### PR TITLE
Slack connector

### PR DESCRIPTION
**Pull request by uocnb**
Add Slack connector with slack bot:
- OAuth authentication workflow and token storage
- Supported slash commands:
  - /meeds_hello
  - /meeds_sign_in
  - /meeds_whoami
  - /meeds_clear
  - /meeds_kudos
  - /meeds_send_kudos
- Event hook with slack challenge
- Unitest for Slack account DAO token storage
- Mock for Space and IdentityManager service

### CODE REVIEW

**Comment by jeremi** [comment]
- Could we rename `exo.properties` to `meeds.properties`?
- Could the slack token be stored in the database instead of the config? (So we do not need to redeploy)
- Can the command be `meeds` and `hello`, `signin`, `whoami` become parameters? So the user just type `/meeds hello` instead of `/meeds_hello`
- For `/meeds_send_kudos` can we use the @person syntax instead for the person to give the kudo? 
- can we improve the callback URLs?

**Comment by uocnb** [comment]
Hi @jeremi 

> * Could we rename `exo.properties` to `meeds.properties`?

The `exo.properties` file is configured as default system properties in the Meeds's tomcat, I think we should make change in meeds repo instead. https://github.com/Meeds-io/meeds/blob/develop/services/plf-configuration/src/main/resources/conf/platform/configuration.xml#L33.


> * Could the slack token be stored in the database instead of the config? (So we do not need to redeploy)

Yes, should we store other related slack credentials like `CLIENT_ID`, `SIGNING_SECRET` etc to the same table in the database together with bot token? 


> * Can the command be `meeds` and `hello`, `signin`, `whoami` become parameters? So the user just type `/meeds hello` instead of `/meeds_hello`

Yes, it can be.


> * For `/meeds_send_kudos` can we use the @person syntax instead for the person to give the kudo?

We are store the linked Slack user in the Meeds's DB, by using slack mention syntax we will need both sender and receiver authorized to Meeds or force them to use same email on both system. Without this we cannot lookup for the right user that mentioned.


> * can we improve the callback URL pages?

Yes, we should have better UI and text there.

**Comment by jeremi** [comment]
@uocnb a little more feedback gathered from other people who saw the video:
- Can we support also the `bot` API token? That would avoid having each user to sign-in. Instead, an admin would do the mapping or could check a box to map my email address automatically (could be OK if they use SSO I guess). That would also help with my second point

**Comment by jeremi** [comment]
> Yes, should we store other related slack credentials like `CLIENT_ID`, `SIGNING_SECRET` etc to the same table in the database together with bot token?
Yes. It will be deployed as Docker instance so it will be easier.

**Pull request closed without merging**
